Add type field to Environment configuration, indicating Kubernetes vs OpenShift
redhat-appstudio/application-api pull request #45
Opened 2023-04-12 00:38 UTC by jgwest

As discussed on [RHTAP-129/STONE-264](https://docs.google.com/document/d/1ihFNBy3FsW3R3Jyt9zLAM6TpIGYH2tkFmFZTiD2rsBw/edit#heading=h.5o6ujoz34zty) we need a field to describe whether the target K8s environment is Kubernetes or OpenShift. 

This is a first stab at such a field, feel free to provide comments on the PR.

2023-04-12 13:25 UTC, rohitkrai03 requested changes

2023-04-13 13:24 UTC, jgwest commented on api/v1alpha1/environment_types.go
> +	EnvironmentType ConfigurationEnvironmentType `json:"environmentType,omitempty"`
:+1: from me, I've updated the PR, let me know what you think.

2023-04-17 16:06 UTC, rohitkrai03 commented
/lgtm

2023-04-17 21:14 UTC, jgwest commented
Thanks @rohitkrai03!

2023-04-17 21:15 UTC, merged